export const GET_CHAT_GROUPS = "GET_CHAT_GROUPS";
export const CHAT_GROUPS_SUCCESS = "CHAT_GROUPS_SUCCESS";
export const CHAT_GROUPS_FAILED = "CHAT_GROUPS_FAILED";
export const SELECT_GROUP = "SELECT_GROUP";
export const GET_MESSAGES = "GET_MESSAGES";
export const GET_MESSAGES_SUCCESS = "GET_MESSAGES_SUCCESS";
export const GET_MESSAGES_FAILURE = "GET_MESSAGES_FAILURE";
export const CLEAR_ACTIVE = "CLEAR_ACTIVE";
