# Generated by Django 3.2.3 on 2021-06-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='group_name',
            field=models.CharField(default='Chat', max_length=30),
        ),
    ]
